CREATE TABLE IF NOT EXISTS security_audit_logs (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rule_id VARCHAR2(50) NOT NULL,
    resource VARCHAR2(255) NOT NULL,
    status VARCHAR2(50) NOT NULL,
    details CLOB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
