CREATE TABLE IF NOT EXISTS media_transcripts (
    id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    media_name VARCHAR2(255) NOT NULL,
    transcript CLOB NOT NULL,
    confidence_score NUMBER(5,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
